server:
  port: 7091

spring:
  application:
    name: seata-server

logging:
  config: classpath:logback-spring.xml
  file:
    path: ${log.home:${user.home}/logs/seata}
  extend:
    logstash-appender:
      destination: 127.0.0.1:4560
    kafka-appender:
      bootstrap-servers: 127.0.0.1:9092
      topic: logback_to_logstash

console:
  user:
    username: seata
    password: seata
seata:
  config:
    # support: nacos, consul, apollo, zk, etcd3
    #服务配置中心选择nacos
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace:
      #后续自己在nacos里面新建,不想新建SEATA_GROUP，就写DEFAULT_GROUP
      group: DEFAULT_GROUP
      username: nacos
      password: nacos
  registry:
    # support: nacos, eureka, redis, zk, consul, etcd3, sofa
    #服务注册中心选择nacos
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: DEFAULT_GROUP
      namespace:
      cluster: default
      username: nacos
      password: nacos

  store:
    # support: file 、 db 、 redis 、 raft
    #这里就是我们参考官网的mysql.sql文件中要的条件db，使用数据库存储
    mode: db
    db:
      datasource: druid
      db-type: mysql
      #这里我们是8.0版本的驱动换一下
      driver-class-name: com.mysql.cj.jdbc.Driver
      #这里说明一下，我的MySQL8.0的端口被我改成3307了
      url: jdbc:mysql://app.deehero.com:60014/seata?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      user: root
      password: root
      min-conn: 10
      max-conn: 100
      #这里分别对应我们创建的仨表
      global-table: global_table
      branch-table: branch_table
      lock-table: lock_table
      distributed-lock-table: distributed_lock
      query-limit: 1000
      max-wait: 5000
  #  server:
  #    service-port: 8091 #If not configured, the default is '${server.port} + 1000'
  security:
    secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
    tokenValidityInMilliseconds: 1800000
    ignore:
      urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.jpeg,/**/*.ico,/api/v1/auth/login,/metadata/v1/**

