server:
  port: 10020
  error:
    include-message: always
  undertow:
    max-http-post-size: 0
    #    threads:
    #      io: 4
    #      worker: 32
    buffer-size: 1024
    direct-buffers: true

spring:
  application:
    name: "@artifactId@"
  profiles:
    active: dev,mysql-dev
    include: upgrade,db

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
      enabled: true

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss

  security:
    validate-code:
      enabled: false
    bad-creadentials:
      enabled: false
      count: 5
      timeout: 30 #单位为分钟
    ignore-urls:
      - /security-setting/validate-code
      - /type
    authority-urls:
      - url: /system/**
        authorities: superadmin,system
      - url: /resource/**
        authorities: superadmin,resource,deptmanager
      - url: /organization/**
        authorities: superadmin,deptmanager,manager,systemmanager,unitadmin
      - url: /user/**
        authorities: superadmin,deptmanager,manager,systemmanager,unitadmin
      - url: /role/**
        authorities: superadmin,role
    oauth2:
      server:
        access-token-timeout: 360 #单位为分钟
        concurrent-access: true
        concurrent-shared: false

#  redis:
#    host: 127.0.0.1
#    port: 6379
#    lettuce:
#      pool:
#        max-active: 16

snowflake:
  worker-id: 1

mybatis:
  mapper-locations:
    - classpath*:/mapper/*Mapper.xml
  configuration:
    jdbc-type-for-null: 'NULL'
    use-actual-param-name: true
    map-underscore-to-camel-case: true

