spring:
  redis:
    lettuce:
      shutdown-timeout: 100 # 关闭超时时间(ms)
      pool:
        max-active: 2 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 2 # 连接池中的最大空闲连接
        max-wait: 3000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接


springfox:
  documentation:
    service-url: http://${spring.cloud.client.ip-address}:${server.port}
    service-name: ${spring.application.name}